import {
  TokenHolding,
  CryptoNarrative,
  AirdropOpportunity,
  TradingSignal,
  HotTopic,
  VideoIdea,
  HealthMetrics,
  DashboardStats,
} from "@/types"

export const mockTokens: TokenHolding[] = [
  {
    mint: "So11111111111111111111111111111111111111112",
    symbol: "SOL",
    name: "Solana",
    balance: 125.5,
    usdValue: 18825,
    price: 150,
    change24h: 5.2,
  },
  {
    mint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    symbol: "USDC",
    name: "USD Coin",
    balance: 5000,
    usdValue: 5000,
    price: 1,
    change24h: 0.1,
  },
  {
    mint: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
    symbol: "JUP",
    name: "Jupiter",
    balance: 2500,
    usdValue: 3750,
    price: 1.5,
    change24h: 12.5,
  },
  {
    mint: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    symbol: "BONK",
    name: "Bonk",
    balance: 10000000,
    usdValue: 250,
    price: 0.000025,
    change24h: -3.2,
  },
]

export const mockNarratives: CryptoNarrative[] = [
  {
    id: "1",
    name: "AI Agents",
    category: "Emerging Tech",
    trending: true,
    sentiment: "bullish",
    marketCap: 5200000000,
    change7d: 45.3,
    topProjects: ["VIRTUAL", "AI16Z", "ZEREBRO"],
    description: "AI-powered autonomous agents on blockchain gaining massive traction",
  },
  {
    id: "2",
    name: "Solana DeFi",
    category: "DeFi",
    trending: true,
    sentiment: "bullish",
    marketCap: 12400000000,
    change7d: 28.7,
    topProjects: ["JUP", "JITO", "DRIFT"],
    description: "Solana DeFi ecosystem experiencing renewed growth and innovation",
  },
  {
    id: "3",
    name: "RWA Tokenization",
    category: "Infrastructure",
    trending: false,
    sentiment: "neutral",
    marketCap: 8900000000,
    change7d: 5.2,
    topProjects: ["ONDO", "POLYX", "RIO"],
    description: "Real-world asset tokenization slowly gaining institutional adoption",
  },
]

export const mockAirdrops: AirdropOpportunity[] = [
  {
    id: "1",
    protocol: "Kamino Finance",
    chain: "Solana",
    category: "DeFi",
    estimatedValue: 1500,
    effort: "medium",
    deadline: "March 2026",
    requirements: [
      "Provide liquidity in USDC-SOL pool",
      "Stake KMNO tokens",
      "Complete at least 10 transactions",
    ],
    status: "active",
    userProgress: 65,
  },
  {
    id: "2",
    protocol: "MarginFi",
    chain: "Solana",
    category: "Lending",
    estimatedValue: 2000,
    effort: "low",
    deadline: "Q2 2026",
    requirements: [
      "Supply assets as collateral",
      "Borrow against collateral",
      "Hold position for 30+ days",
    ],
    status: "active",
    userProgress: 80,
  },
  {
    id: "3",
    protocol: "Tensor",
    chain: "Solana",
    category: "NFT",
    estimatedValue: 800,
    effort: "high",
    requirements: [
      "List NFTs on marketplace",
      "Make trades totaling >5 SOL",
      "Provide liquidity in pools",
      "Maintain activity for 60 days",
    ],
    status: "active",
    userProgress: 30,
  },
]

export const mockSignals: TradingSignal[] = [
  {
    id: "1",
    token: "JUP",
    signal: "buy",
    confidence: 85,
    price: 1.50,
    targetPrice: 2.25,
    stopLoss: 1.30,
    reasoning: "Strong upward momentum with increased DEX volume. Breaking resistance at $1.45.",
    timestamp: new Date(),
  },
  {
    id: "2",
    token: "PYTH",
    signal: "buy",
    confidence: 72,
    price: 0.45,
    targetPrice: 0.65,
    stopLoss: 0.38,
    reasoning: "Oracle expansion to new chains imminent. Accumulation pattern forming.",
    timestamp: new Date(),
  },
  {
    id: "3",
    token: "WIF",
    signal: "hold",
    confidence: 65,
    price: 2.80,
    targetPrice: 3.50,
    stopLoss: 2.40,
    reasoning: "Consolidating after recent pump. Wait for clear direction before entry.",
    timestamp: new Date(),
  },
]

export const mockTopics: HotTopic[] = [
  {
    id: "1",
    topic: "Solana Phone Chapter 2 Launch",
    category: "Hardware",
    volume: 125000,
    sentiment: 0.78,
    trending: "up",
    mentions24h: 8500,
    keyInfluencers: ["@aeyakovenko", "@rajgokal"],
    relatedTokens: ["SOL", "BONK"],
  },
  {
    id: "2",
    topic: "Jupiter LFG Launchpad",
    category: "DeFi",
    volume: 98000,
    sentiment: 0.82,
    trending: "up",
    mentions24h: 6200,
    keyInfluencers: ["@weremeow"],
    relatedTokens: ["JUP", "JLP"],
  },
  {
    id: "3",
    topic: "AI Agent Narratives",
    category: "AI",
    volume: 156000,
    sentiment: 0.85,
    trending: "up",
    mentions24h: 12400,
    keyInfluencers: ["@shawmakesmagic", "@pmairca"],
    relatedTokens: ["VIRTUAL", "AI16Z"],
  },
]

export const mockVideoIdeas: VideoIdea[] = [
  {
    id: "1",
    title: "Top 5 Solana Airdrops You NEED to Farm Right Now",
    topic: "Airdrops",
    priority: "high",
    estimatedViews: 50000,
    trendinessScore: 92,
    relatedNarratives: ["Solana DeFi", "Airdrops"],
    hooks: [
      "These airdrops could be worth $10k+ each",
      "Only 2 weeks left on some of these",
      "I'm personally farming all 5",
    ],
    keyPoints: [
      "Kamino strategy breakdown",
      "MarginFi step-by-step guide",
      "Tensor NFT farming tips",
    ],
    deadline: "Jan 15, 2026",
    status: "planned",
  },
  {
    id: "2",
    title: "AI Agents on Solana Are EXPLODING (How to Invest)",
    topic: "AI Agents",
    priority: "high",
    estimatedViews: 75000,
    trendinessScore: 95,
    relatedNarratives: ["AI Agents", "Solana"],
    hooks: [
      "This narrative is up 300% this month",
      "Major protocols launching soon",
      "Early entry opportunity",
    ],
    keyPoints: [
      "What are AI agents?",
      "Top projects to watch",
      "How to position yourself",
    ],
    status: "idea",
  },
  {
    id: "3",
    title: "Solana Phone Chapter 2 Unboxing + dApp Review",
    topic: "Hardware",
    priority: "medium",
    estimatedViews: 35000,
    trendinessScore: 78,
    relatedNarratives: ["Solana Ecosystem"],
    hooks: [
      "Exclusive first look",
      "Testing all new features",
      "Is it worth the upgrade?",
    ],
    keyPoints: [
      "Hardware improvements",
      "Pre-installed dApps",
      "Comparison with Chapter 1",
    ],
    deadline: "Jan 20, 2026",
    status: "filming",
  },
]

export const mockHealthMetrics: HealthMetrics = {
  date: new Date().toISOString(),
  weight: 175,
  steps: 12450,
  sleep: 7.5,
  calories: 2100,
  water: 80,
  workout: {
    type: "strength training",
    duration: 45,
    intensity: "high",
    caloriesBurned: 380,
    notes: "Upper body focus - great pump today",
  },
}

export const mockDashboardStats: DashboardStats = {
  totalPortfolioValue: 27825,
  portfolioChange24h: 5.8,
  activeAirdrops: 3,
  pendingOpportunities: 3,
  healthStreak: 12,
  contentIdeas: 3,
}
